DROP TABLE IF EXISTS CODE_SYSTEM;
DROP TABLE IF EXISTS CODE_SYSTEM_CONCEPT;
DROP TABLE IF EXISTS CODE_SYSTEM_VERSION;
DROP TABLE IF EXISTS DESIGNATION;
DROP TABLE IF EXISTS TRANSCODING_ASSOCIATION;
DROP TABLE IF EXISTS VALUE_SET;
DROP TABLE IF EXISTS VALUE_SET_VERSION;
DROP TABLE IF EXISTS X_CONCEPT_VALUE_SET;

CREATE TABLE CODE_SYSTEM (
  ID          BIGINT AUTO_INCREMENT NOT NULL,
  OID         VARCHAR(255),
  NAME        VARCHAR(255),
  DESCRIPTION VARCHAR(4000),
  PRIMARY KEY (ID)
);

CREATE TABLE CODE_SYSTEM_VERSION (
  ID                  BIGINT AUTO_INCREMENT NOT NULL,
  FULL_NAME           VARCHAR(255),
  LOCAL_NAME          VARCHAR(255),
  PREVIOUS_VERSION_ID BIGINT,
  EFFECTIVE_DATE      TIMESTAMP,
  RELEASE_DATE        TIMESTAMP,
  STATUS              VARCHAR(255),
  STATUS_DATE         TIMESTAMP,
  DESCRIPTION         VARCHAR(4000),
  COPYRIGHT           VARCHAR(255),
  SOURCE              VARCHAR(255),
  CODE_SYSTEM_ID      BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE CODE_SYSTEM_CONCEPT (
  ID                     BIGINT AUTO_INCREMENT NOT NULL,
  CODE                   VARCHAR(255),
  STATUS                 VARCHAR(255),
  STATUS_DATE            TIMESTAMP,
  DEFINITION             VARCHAR(4000),
  CODE_SYSTEM_VERSION_ID BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE DESIGNATION (
  ID                     BIGINT AUTO_INCREMENT NOT NULL,
  DESIGNATION            VARCHAR(4000),
  LANGUAGE_CODE          VARCHAR(255),
  TYPE                   VARCHAR(255),
  IS_PREFERRED           BOOLEAN,
  STATUS                 VARCHAR(255),
  STATUS_DATE            TIMESTAMP,
  CODE_SYSTEM_CONCEPT_ID BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE TRANSCODING_ASSOCIATION (
  ID                         BIGINT AUTO_INCREMENT NOT NULL,
  TRANSCODING_ASSOCIATION_ID BIGINT                NOT NULL,
  TARGET_CONCEPT_ID          BIGINT,
  SOURCE_CONCEPT_ID          BIGINT,
  QUALITY                    VARCHAR(255),
  STATUS                     VARCHAR(255),
  STATUS_DATE                TIMESTAMP,
  PRIMARY KEY (ID)
);

CREATE TABLE VALUE_SET (
  ID                    BIGINT AUTO_INCREMENT NOT NULL,
  OID                   VARCHAR(255),
  EPSOS_NAME            VARCHAR(255),
  DESCRIPTION           VARCHAR(4000),
  PARENT_CODE_SYSTEM_ID BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE VALUE_SET_VERSION (
  ID                  BIGINT AUTO_INCREMENT NOT NULL,
  VERSION_NAME        VARCHAR(255),
  EFFECTIVE_DATE      TIMESTAMP,
  RELEASE_DATE        TIMESTAMP,
  STATUS              VARCHAR(255),
  STATUS_DATE         TIMESTAMP,
  DESCRIPTION         VARCHAR(4000),
  PREVIOUS_VERSION_ID BIGINT,
  VALUE_SET_ID        BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE X_CONCEPT_VALUE_SET (
  CODE_SYSTEM_CONCEPT_ID BIGINT NOT NULL,
  VALUE_SET_VERSION_ID   BIGINT NOT NULL,
  PRIMARY KEY (CODE_SYSTEM_CONCEPT_ID, VALUE_SET_VERSION_ID)
);

ALTER TABLE CODE_SYSTEM_CONCEPT
  ADD CONSTRAINT FK_CODE_SYSTEM_VERSION_ID
FOREIGN KEY (CODE_SYSTEM_VERSION_ID)
REFERENCES CODE_SYSTEM_VERSION (ID);

ALTER TABLE CODE_SYSTEM_VERSION
  ADD CONSTRAINT FK_CODE_SYSTEM_ID
FOREIGN KEY (CODE_SYSTEM_ID)
REFERENCES CODE_SYSTEM (ID);

ALTER TABLE DESIGNATION
  ADD CONSTRAINT FK_CODE_SYSTEM_CONCEPT_ID
FOREIGN KEY (CODE_SYSTEM_CONCEPT_ID)
REFERENCES CODE_SYSTEM_CONCEPT (ID);

ALTER TABLE TRANSCODING_ASSOCIATION
  ADD CONSTRAINT FK_SOURCE_CONCEPT_ID
FOREIGN KEY (SOURCE_CONCEPT_ID)
REFERENCES CODE_SYSTEM_CONCEPT (ID);

ALTER TABLE TRANSCODING_ASSOCIATION
  ADD CONSTRAINT FK_TARGET_CONCEPT_ID
FOREIGN KEY (TARGET_CONCEPT_ID)
REFERENCES CODE_SYSTEM_CONCEPT (ID);

ALTER TABLE VALUE_SET
  ADD CONSTRAINT FK_PARENT_CODE_SYSTEM_ID
FOREIGN KEY (PARENT_CODE_SYSTEM_ID)
REFERENCES CODE_SYSTEM (ID);

ALTER TABLE VALUE_SET_VERSION
  ADD CONSTRAINT FK_PREVIOUS_VERSION_ID
FOREIGN KEY (PREVIOUS_VERSION_ID)
REFERENCES VALUE_SET_VERSION;

ALTER TABLE VALUE_SET_VERSION
  ADD CONSTRAINT FK_VALUE_SET_ID
FOREIGN KEY (VALUE_SET_ID)
REFERENCES VALUE_SET;

ALTER TABLE X_CONCEPT_VALUE_SET
  ADD CONSTRAINT FK_CODE_SYSTEM_CONCEPT_ID
FOREIGN KEY (CODE_SYSTEM_CONCEPT_ID)
REFERENCES CODE_SYSTEM_CONCEPT(ID);

ALTER TABLE X_CONCEPT_VALUE_SET
  ADD CONSTRAINT FK_VALUE_SET_VERSION_ID
FOREIGN KEY (VALUE_SET_VERSION_ID)
REFERENCES VALUE_SET_VERSION(ID);