package eu.epsos.configmanager.database.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Property generated by hbm2java
 */
@Entity
@Table(name = "property")
public class Property implements java.io.Serializable {

    @Id
    private String name;

    @Column(name = "value")
    private String value;

    @Column(name = "isSmp")
    private Boolean isSMP;

    public Property() {
    }

    public Property(String name) {
        this.name = name;
    }

    public Property(String name, String value) {
        this.name = name;
        this.value = value;
    }

    public String getName() {
        return this.name;
    }

    public void setKey(String name) {
        this.name = name;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Boolean isSMP() {
        return this.isSMP;
    }
}
