
package epsos.ccd.carecom.tsam.synchronizer.webservice.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CommonTerminologyService2.0", targetNamespace = "http://cts2.webservice.ht.carecom.dk/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommonTerminologyService20 {


    /**
     * 
     * @param designationLanguageCode
     * @param conceptID
     * @param designationType
     * @param designationStatus
     * @param deltaEndTime
     * @param deltaStartTime
     * @param codeSystemOid
     * @param designationValidFrom
     * @param codeSystemId
     * @param conceptExternalCode
     * @return
     *     returns java.util.List<epsos.ccd.carecom.tsam.synchronizer.webservice.client.Designation>
     * @throws HealthTermWebServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listDesignations", targetNamespace = "http://cts2.webservice.ht.carecom.dk/", className = "epsos.ccd.carecom.tsam.synchronizer.webservice.client.ListDesignations")
    @ResponseWrapper(localName = "listDesignationsResponse", targetNamespace = "http://cts2.webservice.ht.carecom.dk/", className = "epsos.ccd.carecom.tsam.synchronizer.webservice.client.ListDesignationsResponse")
    public List<Designation> listDesignations(
        @WebParam(name = "codeSystemId", targetNamespace = "")
        List<Long> codeSystemId,
        @WebParam(name = "codeSystemOid", targetNamespace = "")
        List<String> codeSystemOid,
        @WebParam(name = "conceptID", targetNamespace = "")
        List<Long> conceptID,
        @WebParam(name = "conceptExternalCode", targetNamespace = "")
        List<String> conceptExternalCode,
        @WebParam(name = "designationType", targetNamespace = "")
        List<Integer> designationType,
        @WebParam(name = "designationLanguageCode", targetNamespace = "")
        List<String> designationLanguageCode,
        @WebParam(name = "designationValidFrom", targetNamespace = "")
        XMLGregorianCalendar designationValidFrom,
        @WebParam(name = "designationStatus", targetNamespace = "")
        List<Integer> designationStatus,
        @WebParam(name = "deltaStartTime", targetNamespace = "")
        XMLGregorianCalendar deltaStartTime,
        @WebParam(name = "deltaEndTime", targetNamespace = "")
        XMLGregorianCalendar deltaEndTime)
        throws HealthTermWebServiceException_Exception
    ;

    /**
     * 
     * @param valueSetName
     * @param valueSetOid
     * @param deltaEndTime
     * @param valueSetId
     * @param deltaStartTime
     * @param valueSetValidFrom
     * @param codeSystemOid
     * @param codeSystemId
     * @param valueSetStatus
     * @return
     *     returns java.util.List<epsos.ccd.carecom.tsam.synchronizer.webservice.client.ValueSet>
     * @throws HealthTermWebServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listValueSets", targetNamespace = "http://cts2.webservice.ht.carecom.dk/", className = "epsos.ccd.carecom.tsam.synchronizer.webservice.client.ListValueSets")
    @ResponseWrapper(localName = "listValueSetsResponse", targetNamespace = "http://cts2.webservice.ht.carecom.dk/", className = "epsos.ccd.carecom.tsam.synchronizer.webservice.client.ListValueSetsResponse")
    public List<ValueSet> listValueSets(
        @WebParam(name = "codeSystemId", targetNamespace = "")
        List<Long> codeSystemId,
        @WebParam(name = "codeSystemOid", targetNamespace = "")
        List<String> codeSystemOid,
        @WebParam(name = "valueSetId", targetNamespace = "")
        List<Long> valueSetId,
        @WebParam(name = "valueSetOid", targetNamespace = "")
        List<String> valueSetOid,
        @WebParam(name = "valueSetName", targetNamespace = "")
        String valueSetName,
        @WebParam(name = "valueSetValidFrom", targetNamespace = "")
        XMLGregorianCalendar valueSetValidFrom,
        @WebParam(name = "valueSetStatus", targetNamespace = "")
        List<Integer> valueSetStatus,
        @WebParam(name = "deltaStartTime", targetNamespace = "")
        XMLGregorianCalendar deltaStartTime,
        @WebParam(name = "deltaEndTime", targetNamespace = "")
        XMLGregorianCalendar deltaEndTime)
        throws HealthTermWebServiceException_Exception
    ;

    /**
     * 
     * @param propertyLanguageCode
     * @param propertyStatus
     * @param propertyTypeCode
     * @param propertyTypeId
     * @param deltaEndTime
     * @param propertyValidFrom
     * @param deltaStartTime
     * @param codeSystemOid
     * @param componentId
     * @param codeSystemId
     * @param propertyReferenceId
     * @param conceptExternalCode
     * @return
     *     returns java.util.List<epsos.ccd.carecom.tsam.synchronizer.webservice.client.Property>
     * @throws HealthTermWebServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listProperties", targetNamespace = "http://cts2.webservice.ht.carecom.dk/", className = "epsos.ccd.carecom.tsam.synchronizer.webservice.client.ListProperties")
    @ResponseWrapper(localName = "listPropertiesResponse", targetNamespace = "http://cts2.webservice.ht.carecom.dk/", className = "epsos.ccd.carecom.tsam.synchronizer.webservice.client.ListPropertiesResponse")
    public List<Property> listProperties(
        @WebParam(name = "codeSystemId", targetNamespace = "")
        List<Long> codeSystemId,
        @WebParam(name = "codeSystemOid", targetNamespace = "")
        List<String> codeSystemOid,
        @WebParam(name = "componentId", targetNamespace = "")
        List<Long> componentId,
        @WebParam(name = "conceptExternalCode", targetNamespace = "")
        List<String> conceptExternalCode,
        @WebParam(name = "propertyTypeId", targetNamespace = "")
        List<Integer> propertyTypeId,
        @WebParam(name = "propertyTypeCode", targetNamespace = "")
        List<String> propertyTypeCode,
        @WebParam(name = "propertyReferenceId", targetNamespace = "")
        List<Long> propertyReferenceId,
        @WebParam(name = "propertyLanguageCode", targetNamespace = "")
        List<String> propertyLanguageCode,
        @WebParam(name = "propertyValidFrom", targetNamespace = "")
        XMLGregorianCalendar propertyValidFrom,
        @WebParam(name = "propertyStatus", targetNamespace = "")
        List<Integer> propertyStatus,
        @WebParam(name = "deltaStartTime", targetNamespace = "")
        XMLGregorianCalendar deltaStartTime,
        @WebParam(name = "deltaEndTime", targetNamespace = "")
        XMLGregorianCalendar deltaEndTime)
        throws HealthTermWebServiceException_Exception
    ;

    /**
     * 
     * @param conceptValidFrom
     * @param valueSetOid
     * @param deltaEndTime
     * @param valueSetId
     * @param deltaStartTime
     * @param codeSystemOid
     * @param conceptStatus
     * @param codeSystemId
     * @return
     *     returns java.util.List<epsos.ccd.carecom.tsam.synchronizer.webservice.client.CodeSystemConcept>
     * @throws HealthTermWebServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCodeSystemConcepts", targetNamespace = "http://cts2.webservice.ht.carecom.dk/", className = "epsos.ccd.carecom.tsam.synchronizer.webservice.client.ListCodeSystemConcepts")
    @ResponseWrapper(localName = "listCodeSystemConceptsResponse", targetNamespace = "http://cts2.webservice.ht.carecom.dk/", className = "epsos.ccd.carecom.tsam.synchronizer.webservice.client.ListCodeSystemConceptsResponse")
    public List<CodeSystemConcept> listCodeSystemConcepts(
        @WebParam(name = "codeSystemId", targetNamespace = "")
        List<Long> codeSystemId,
        @WebParam(name = "codeSystemOid", targetNamespace = "")
        List<String> codeSystemOid,
        @WebParam(name = "valueSetId", targetNamespace = "")
        List<Long> valueSetId,
        @WebParam(name = "valueSetOid", targetNamespace = "")
        List<String> valueSetOid,
        @WebParam(name = "conceptValidFrom", targetNamespace = "")
        XMLGregorianCalendar conceptValidFrom,
        @WebParam(name = "conceptStatus", targetNamespace = "")
        List<Integer> conceptStatus,
        @WebParam(name = "deltaStartTime", targetNamespace = "")
        XMLGregorianCalendar deltaStartTime,
        @WebParam(name = "deltaEndTime", targetNamespace = "")
        XMLGregorianCalendar deltaEndTime)
        throws HealthTermWebServiceException_Exception
    ;

    /**
     * 
     * @param codeSystemName
     * @param codeSystemValidFrom
     * @param deltaEndTime
     * @param deltaStartTime
     * @param codeSystemOid
     * @param codeSystemId
     * @param codeSystemDescription
     * @return
     *     returns java.util.List<epsos.ccd.carecom.tsam.synchronizer.webservice.client.CodeSystem>
     * @throws HealthTermWebServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCodeSystems", targetNamespace = "http://cts2.webservice.ht.carecom.dk/", className = "epsos.ccd.carecom.tsam.synchronizer.webservice.client.ListCodeSystems")
    @ResponseWrapper(localName = "listCodeSystemsResponse", targetNamespace = "http://cts2.webservice.ht.carecom.dk/", className = "epsos.ccd.carecom.tsam.synchronizer.webservice.client.ListCodeSystemsResponse")
    public List<CodeSystem> listCodeSystems(
        @WebParam(name = "codeSystemId", targetNamespace = "")
        List<Long> codeSystemId,
        @WebParam(name = "codeSystemOid", targetNamespace = "")
        List<String> codeSystemOid,
        @WebParam(name = "codeSystemName", targetNamespace = "")
        String codeSystemName,
        @WebParam(name = "codeSystemValidFrom", targetNamespace = "")
        XMLGregorianCalendar codeSystemValidFrom,
        @WebParam(name = "codeSystemDescription", targetNamespace = "")
        String codeSystemDescription,
        @WebParam(name = "deltaStartTime", targetNamespace = "")
        XMLGregorianCalendar deltaStartTime,
        @WebParam(name = "deltaEndTime", targetNamespace = "")
        XMLGregorianCalendar deltaEndTime)
        throws HealthTermWebServiceException_Exception
    ;

    /**
     * 
     * @param transcodingSourceConceptId
     * @param transcodingStatus
     * @param deltaEndTime
     * @param transcodingValidFrom
     * @param deltaStartTime
     * @param transcodingTargetConceptId
     * @param transcodingSourceExternalCode
     * @param transcodingTargetExternalCode
     * @return
     *     returns java.util.List<epsos.ccd.carecom.tsam.synchronizer.webservice.client.Transcoding>
     * @throws HealthTermWebServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listTranscodings", targetNamespace = "http://cts2.webservice.ht.carecom.dk/", className = "epsos.ccd.carecom.tsam.synchronizer.webservice.client.ListTranscodings")
    @ResponseWrapper(localName = "listTranscodingsResponse", targetNamespace = "http://cts2.webservice.ht.carecom.dk/", className = "epsos.ccd.carecom.tsam.synchronizer.webservice.client.ListTranscodingsResponse")
    public List<Transcoding> listTranscodings(
        @WebParam(name = "transcodingSourceConceptId", targetNamespace = "")
        List<Long> transcodingSourceConceptId,
        @WebParam(name = "transcodingSourceExternalCode", targetNamespace = "")
        List<String> transcodingSourceExternalCode,
        @WebParam(name = "transcodingTargetConceptId", targetNamespace = "")
        List<Long> transcodingTargetConceptId,
        @WebParam(name = "transcodingTargetExternalCode", targetNamespace = "")
        List<String> transcodingTargetExternalCode,
        @WebParam(name = "transcodingValidFrom", targetNamespace = "")
        XMLGregorianCalendar transcodingValidFrom,
        @WebParam(name = "transcodingStatus", targetNamespace = "")
        List<Integer> transcodingStatus,
        @WebParam(name = "deltaStartTime", targetNamespace = "")
        XMLGregorianCalendar deltaStartTime,
        @WebParam(name = "deltaEndTime", targetNamespace = "")
        XMLGregorianCalendar deltaEndTime)
        throws HealthTermWebServiceException_Exception
    ;

}
