
<wsdl:definitions targetNamespace="http://epsos.eu/"
                  xmlns:tns="http://epsos.eu/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                  xmlns:wsap="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:q1="http://schemas.message.com/Message"
                  xmlns:q2="http://schemas.message.com/Message"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsp1="http://www.w3.org/ns/ws-policy" xmlns:fi="http://java.sun.com/xml/ns/wsit/2006/09/policy/fastinfoset/service" xmlns:tcp="http://java.sun.com/xml/ns/wsit/2006/09/policy/soaptcp/service" xmlns:jaxws="http://java.sun.com/xml/ns/jaxws">


    <wsdl:types>
        <xsd:schema targetNamespace="http://epsos.eu/Imports">
            <xsd:import schemaLocation="service_schema.xsd" namespace="http://schemas.message.com/Message"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="ISecurityTokenService_IssueToken_InputMessage">
        <wsdl:part name="rstMessage" type="q1:MessageBody"/>
    </wsdl:message>
    <wsdl:message name="ISecurityTokenService_IssueToken_OutputMessage">
        <wsdl:part name="IssueTokenResult" type="q2:MessageBody"/>
    </wsdl:message>



    <wsdl:portType name="ISecurityTokenService">
        <wsdl:operation name="IssueToken">
            <wsdl:input wsap:Action="http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Issue" message="tns:ISecurityTokenService_IssueToken_InputMessage"/>
            <wsdl:output wsap:Action="http://schemas.xmlsoap.org/ws/2005/02/trust/RSTR/Issue" message="tns:ISecurityTokenService_IssueToken_OutputMessage"/>
        </wsdl:operation>
    </wsdl:portType>


    <wsdl:binding name="ISecurityTokenService_Binding" type="tns:ISecurityTokenService">
        <wsp1:PolicyReference URI="#ISecurityTokenService_BindingPolicy"/>
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="IssueToken">
            <soap:operation soapAction="http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Issue" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="SecurityTokenService">
        <wsdl:port name="ISecurityTokenService_Port" binding="tns:ISecurityTokenService_Binding">
            <soap:address location="http://localhost:8080/jaxws-sts/sts"/>
        </wsdl:port>
    </wsdl:service>

    <wsp1:Policy wsu:Id="ISecurityTokenService_BindingPolicy">
        <wsp1:ExactlyOne>
            <wsp1:All/>
        </wsp1:ExactlyOne>
    </wsp1:Policy>
</wsdl:definitions>
