/**
 * Copyright (C) 2011, 2012 SRDC Yazilim Arastirma ve Gelistirme ve Danismanlik Tic. Ltd. Sti. <epsos@srdc.com.tr>
 * 
 * This file is part of SRDC epSOS NCP.
 * 
 * SRDC epSOS NCP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * SRDC epSOS NCP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with SRDC epSOS NCP. If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.26 at 04:30:06 PM EEST 
//


package urn.oasis.names.tc.xacml3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:3.0:core:schema:wd-17}RequestDefaults" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:3.0:core:schema:wd-17}Attributes" maxOccurs="unbounded"/>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:3.0:core:schema:wd-17}MultiRequests" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ReturnPolicyIdList" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="CombinedDecision" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestType", propOrder = {
    "requestDefaults",
    "attributes",
    "multiRequests"
})
public class RequestType {

    @XmlElement(name = "RequestDefaults")
    protected RequestDefaultsType requestDefaults;
    @XmlElement(name = "Attributes", required = true)
    protected List<AttributesType> attributes;
    @XmlElement(name = "MultiRequests")
    protected MultiRequestsType multiRequests;
    @XmlAttribute(name = "ReturnPolicyIdList", required = true)
    protected boolean returnPolicyIdList;
    @XmlAttribute(name = "CombinedDecision", required = true)
    protected boolean combinedDecision;

    /**
     * Gets the value of the requestDefaults property.
     * 
     * @return
     *     possible object is
     *     {@link RequestDefaultsType }
     *     
     */
    public RequestDefaultsType getRequestDefaults() {
        return requestDefaults;
    }

    /**
     * Sets the value of the requestDefaults property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestDefaultsType }
     *     
     */
    public void setRequestDefaults(RequestDefaultsType value) {
        this.requestDefaults = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributesType }
     * 
     * 
     */
    public List<AttributesType> getAttributes() {
        if (attributes == null) {
            attributes = new ArrayList<AttributesType>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the multiRequests property.
     * 
     * @return
     *     possible object is
     *     {@link MultiRequestsType }
     *     
     */
    public MultiRequestsType getMultiRequests() {
        return multiRequests;
    }

    /**
     * Sets the value of the multiRequests property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiRequestsType }
     *     
     */
    public void setMultiRequests(MultiRequestsType value) {
        this.multiRequests = value;
    }

    /**
     * Gets the value of the returnPolicyIdList property.
     * 
     */
    public boolean isReturnPolicyIdList() {
        return returnPolicyIdList;
    }

    /**
     * Sets the value of the returnPolicyIdList property.
     * 
     */
    public void setReturnPolicyIdList(boolean value) {
        this.returnPolicyIdList = value;
    }

    /**
     * Gets the value of the combinedDecision property.
     * 
     */
    public boolean isCombinedDecision() {
        return combinedDecision;
    }

    /**
     * Sets the value of the combinedDecision property.
     * 
     */
    public void setCombinedDecision(boolean value) {
        this.combinedDecision = value;
    }

}
