//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.29 at 12:47:48 PM CET 
//


package eu.esens.abb.nonrep.etsi.rem;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdditionalInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdditionalInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="TextualInformation" type="{http://uri.etsi.org/02231/v2#}MultiLangStringType"/>
 *         &lt;element name="OtherInformation" type="{http://uri.etsi.org/02231/v2#}MASSIAnyType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdditionalInformationType", namespace = "http://uri.etsi.org/02231/v2#", propOrder = {
    "textualInformationsAndOtherInformations"
})
@XmlRootElement(name = "AdditionalInformation", namespace = "http://uri.etsi.org/02231/v2#")
public class AdditionalInformation {

    @XmlElements({
        @XmlElement(name = "TextualInformation", type = MultiLangStringType.class),
        @XmlElement(name = "OtherInformation", type = MASSIAnyType.class)
    })
    protected List<java.lang.Object> textualInformationsAndOtherInformations;

    /**
     * Gets the value of the textualInformationsAndOtherInformations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textualInformationsAndOtherInformations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextualInformationsAndOtherInformations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultiLangStringType }
     * {@link MASSIAnyType }
     * 
     * 
     */
    public List<java.lang.Object> getTextualInformationsAndOtherInformations() {
        if (textualInformationsAndOtherInformations == null) {
            textualInformationsAndOtherInformations = new ArrayList<java.lang.Object>();
        }
        return this.textualInformationsAndOtherInformations;
    }

}
