//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.29 at 12:47:48 PM CET 
//


package eu.esens.abb.nonrep.etsi.rem;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CertificateDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertificateDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="X509Certificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="CertID" type="{http://uri.etsi.org/01903/v1.3.2#}CertIDType"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v1#}CertIDAndSignature"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertificateDetailsType", namespace = "http://uri.etsi.org/02640/v1#", propOrder = {
    "certIDAndSignature",
    "certID",
    "x509Certificate"
})
@XmlRootElement(name = "CertificateDetails", namespace = "http://uri.etsi.org/02640/v1#")
public class CertificateDetails {

    @XmlElement(name = "CertIDAndSignature")
    protected CertIDAndSignature certIDAndSignature;
    @XmlElement(name = "CertID")
    protected CertIDType certID;
    @XmlElement(name = "X509Certificate")
    protected byte[] x509Certificate;

    /**
     * Gets the value of the certIDAndSignature property.
     * 
     * @return
     *     possible object is
     *     {@link CertIDAndSignature }
     *     
     */
    public CertIDAndSignature getCertIDAndSignature() {
        return certIDAndSignature;
    }

    /**
     * Sets the value of the certIDAndSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertIDAndSignature }
     *     
     */
    public void setCertIDAndSignature(CertIDAndSignature value) {
        this.certIDAndSignature = value;
    }

    /**
     * Gets the value of the certID property.
     * 
     * @return
     *     possible object is
     *     {@link CertIDType }
     *     
     */
    public CertIDType getCertID() {
        return certID;
    }

    /**
     * Sets the value of the certID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertIDType }
     *     
     */
    public void setCertID(CertIDType value) {
        this.certID = value;
    }

    /**
     * Gets the value of the x509Certificate property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getX509Certificate() {
        return x509Certificate;
    }

    /**
     * Sets the value of the x509Certificate property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setX509Certificate(byte[] value) {
        this.x509Certificate = ((byte[]) value);
    }

}
