//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.29 at 12:47:48 PM CET 
//


package eu.esens.abb.nonrep.etsi.rem;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CertIDAndSignatureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertIDAndSignatureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IssuerSerial" type="{http://uri.etsi.org/01903/v1.3.2#}DigestAlgAndValueType"/>
 *         &lt;element name="tbsCertificateDigestDetails" type="{http://uri.etsi.org/01903/v1.3.2#}DigestAlgAndValueType"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v1#}CertSignatureDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertIDAndSignatureType", namespace = "http://uri.etsi.org/02640/v1#", propOrder = {
    "issuerSerial",
    "tbsCertificateDigestDetails",
    "certSignatureDetails"
})
@XmlRootElement(name = "CertIDAndSignature", namespace = "http://uri.etsi.org/02640/v1#")
public class CertIDAndSignature {

    @XmlElement(name = "IssuerSerial", required = true)
    protected DigestAlgAndValueType issuerSerial;
    @XmlElement(required = true)
    protected DigestAlgAndValueType tbsCertificateDigestDetails;
    @XmlElement(name = "CertSignatureDetails", required = true)
    protected CertSignatureDetails certSignatureDetails;

    /**
     * Gets the value of the issuerSerial property.
     * 
     * @return
     *     possible object is
     *     {@link DigestAlgAndValueType }
     *     
     */
    public DigestAlgAndValueType getIssuerSerial() {
        return issuerSerial;
    }

    /**
     * Sets the value of the issuerSerial property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigestAlgAndValueType }
     *     
     */
    public void setIssuerSerial(DigestAlgAndValueType value) {
        this.issuerSerial = value;
    }

    /**
     * Gets the value of the tbsCertificateDigestDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DigestAlgAndValueType }
     *     
     */
    public DigestAlgAndValueType getTbsCertificateDigestDetails() {
        return tbsCertificateDigestDetails;
    }

    /**
     * Sets the value of the tbsCertificateDigestDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigestAlgAndValueType }
     *     
     */
    public void setTbsCertificateDigestDetails(DigestAlgAndValueType value) {
        this.tbsCertificateDigestDetails = value;
    }

    /**
     * Gets the value of the certSignatureDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CertSignatureDetails }
     *     
     */
    public CertSignatureDetails getCertSignatureDetails() {
        return certSignatureDetails;
    }

    /**
     * Sets the value of the certSignatureDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertSignatureDetails }
     *     
     */
    public void setCertSignatureDetails(CertSignatureDetails value) {
        this.certSignatureDetails = value;
    }

}
