//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.29 at 12:47:48 PM CET 
//


package eu.esens.abb.nonrep.etsi.rem;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OtherTSLPointersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OtherTSLPointersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/02231/v2#}OtherTSLPointer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtherTSLPointersType", namespace = "http://uri.etsi.org/02231/v2#", propOrder = {
    "otherTSLPointer"
})
@XmlRootElement(name = "PointersToOtherTSL", namespace = "http://uri.etsi.org/02231/v2#")
public class PointersToOtherTSL {

    @XmlElement(name = "OtherTSLPointer", required = true)
    protected OtherTSLPointer otherTSLPointer;

    /**
     * Gets the value of the otherTSLPointer property.
     * 
     * @return
     *     possible object is
     *     {@link OtherTSLPointer }
     *     
     */
    public OtherTSLPointer getOtherTSLPointer() {
        return otherTSLPointer;
    }

    /**
     * Sets the value of the otherTSLPointer property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherTSLPointer }
     *     
     */
    public void setOtherTSLPointer(OtherTSLPointer value) {
        this.otherTSLPointer = value;
    }

}
