//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.29 at 12:47:48 PM CET 
//


package eu.esens.abb.nonrep.etsi.rem;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecipientsDelegatesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecipientsDelegatesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="DelegateDetails" type="{http://uri.etsi.org/02640/v1#}EntityDetailsType"/>
 *         &lt;element name="DelegatingRecipients" type="{http://uri.etsi.org/02640/v1#}ListOfIntegers"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecipientsDelegatesType", namespace = "http://uri.etsi.org/02640/v1#", propOrder = {
    "delegateDetailsAndDelegatingRecipients"
})
@XmlRootElement(name = "RecipientsDelegatesDetails", namespace = "http://uri.etsi.org/02640/v1#")
public class RecipientsDelegatesDetails {

    @XmlElementRefs({
        @XmlElementRef(name = "DelegatingRecipients", namespace = "http://uri.etsi.org/02640/v1#", type = JAXBElement.class),
        @XmlElementRef(name = "DelegateDetails", namespace = "http://uri.etsi.org/02640/v1#", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> delegateDetailsAndDelegatingRecipients;

    /**
     * Gets the value of the delegateDetailsAndDelegatingRecipients property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delegateDetailsAndDelegatingRecipients property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelegateDetailsAndDelegatingRecipients().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link BigInteger }{@code >}{@code >}
     * {@link JAXBElement }{@code <}{@link EntityDetailsType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getDelegateDetailsAndDelegatingRecipients() {
        if (delegateDetailsAndDelegatingRecipients == null) {
            delegateDetailsAndDelegatingRecipients = new ArrayList<JAXBElement<?>>();
        }
        return this.delegateDetailsAndDelegatingRecipients;
    }

}
