//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.29 at 12:47:48 PM CET 
//


package eu.esens.abb.nonrep.etsi.rem;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for REMEvidenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REMEvidenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/02640/v1#}EventCode" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v1#}EventReasons" minOccurs="0"/>
 *         &lt;element name="EvidenceIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v1#}EvidenceIssuerPolicyID" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v1#}EvidenceIssuerDetails"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v1#}SenderAuthenticationDetails" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v1#}RecipientAuthenticationDetails" minOccurs="0"/>
 *         &lt;element name="EventTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="SubmissionTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ReplyTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v1#}SenderDetails"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v1#}RecipientsDetails"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v1#}RecipientsDelegatesDetails" minOccurs="0"/>
 *         &lt;element name="EvidenceRefersToRecipient" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v1#}SenderMessageDetails" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v1#}NotificationMessageDetails" minOccurs="0"/>
 *         &lt;element name="ForwardedToExternalSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v1#}TransactionLogInformation" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v1#}Extensions" minOccurs="0"/>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REMEvidenceType", namespace = "http://uri.etsi.org/02640/v1#", propOrder = {
    "eventCode",
    "eventReasons",
    "evidenceIdentifier",
    "evidenceIssuerPolicyID",
    "evidenceIssuerDetails",
    "senderAuthenticationDetails",
    "recipientAuthenticationDetails",
    "eventTime",
    "submissionTime",
    "replyTo",
    "senderDetails",
    "recipientsDetails",
    "recipientsDelegatesDetails",
    "evidenceRefersToRecipient",
    "senderMessageDetails",
    "notificationMessageDetails",
    "forwardedToExternalSystem",
    "transactionLogInformation",
    "extensions",
    "signature"
})
public class REMEvidenceType {

    @XmlElement(name = "EventCode")
    @XmlSchemaType(name = "anyURI")
    protected String eventCode;
    @XmlElement(name = "EventReasons")
    protected EventReasons eventReasons;
    @XmlElement(name = "EvidenceIdentifier", required = true)
    protected String evidenceIdentifier;
    @XmlElement(name = "EvidenceIssuerPolicyID")
    protected EvidenceIssuerPolicyID evidenceIssuerPolicyID;
    @XmlElement(name = "EvidenceIssuerDetails", required = true)
    protected EntityDetailsType evidenceIssuerDetails;
    @XmlElement(name = "SenderAuthenticationDetails")
    protected AuthenticationDetailsType senderAuthenticationDetails;
    @XmlElement(name = "RecipientAuthenticationDetails")
    protected AuthenticationDetailsType recipientAuthenticationDetails;
    @XmlElement(name = "EventTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eventTime;
    @XmlElement(name = "SubmissionTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar submissionTime;
    @XmlElement(name = "ReplyTo")
    protected String replyTo;
    @XmlElement(name = "SenderDetails", required = true)
    protected EntityDetailsType senderDetails;
    @XmlElement(name = "RecipientsDetails", required = true)
    protected RecipientsDetails recipientsDetails;
    @XmlElement(name = "RecipientsDelegatesDetails")
    protected RecipientsDelegatesDetails recipientsDelegatesDetails;
    @XmlElement(name = "EvidenceRefersToRecipient")
    protected BigInteger evidenceRefersToRecipient;
    @XmlElement(name = "SenderMessageDetails")
    protected MessageDetailsType senderMessageDetails;
    @XmlElement(name = "NotificationMessageDetails")
    protected MessageDetailsType notificationMessageDetails;
    @XmlElement(name = "ForwardedToExternalSystem")
    protected String forwardedToExternalSystem;
    @XmlElement(name = "TransactionLogInformation")
    protected TransactionLogInformation transactionLogInformation;
    @XmlElement(name = "Extensions")
    protected Extensions extensions;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#")
    protected Signature signature;
    @XmlAttribute(required = true)
    protected String version;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the eventCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventCode() {
        return eventCode;
    }

    /**
     * Sets the value of the eventCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventCode(String value) {
        this.eventCode = value;
    }

    /**
     * Gets the value of the eventReasons property.
     * 
     * @return
     *     possible object is
     *     {@link EventReasons }
     *     
     */
    public EventReasons getEventReasons() {
        return eventReasons;
    }

    /**
     * Sets the value of the eventReasons property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventReasons }
     *     
     */
    public void setEventReasons(EventReasons value) {
        this.eventReasons = value;
    }

    /**
     * Gets the value of the evidenceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvidenceIdentifier() {
        return evidenceIdentifier;
    }

    /**
     * Sets the value of the evidenceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvidenceIdentifier(String value) {
        this.evidenceIdentifier = value;
    }

    /**
     * Gets the value of the evidenceIssuerPolicyID property.
     * 
     * @return
     *     possible object is
     *     {@link EvidenceIssuerPolicyID }
     *     
     */
    public EvidenceIssuerPolicyID getEvidenceIssuerPolicyID() {
        return evidenceIssuerPolicyID;
    }

    /**
     * Sets the value of the evidenceIssuerPolicyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvidenceIssuerPolicyID }
     *     
     */
    public void setEvidenceIssuerPolicyID(EvidenceIssuerPolicyID value) {
        this.evidenceIssuerPolicyID = value;
    }

    /**
     * Gets the value of the evidenceIssuerDetails property.
     * 
     * @return
     *     possible object is
     *     {@link EntityDetailsType }
     *     
     */
    public EntityDetailsType getEvidenceIssuerDetails() {
        return evidenceIssuerDetails;
    }

    /**
     * Sets the value of the evidenceIssuerDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityDetailsType }
     *     
     */
    public void setEvidenceIssuerDetails(EntityDetailsType value) {
        this.evidenceIssuerDetails = value;
    }

    /**
     * Gets the value of the senderAuthenticationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationDetailsType }
     *     
     */
    public AuthenticationDetailsType getSenderAuthenticationDetails() {
        return senderAuthenticationDetails;
    }

    /**
     * Sets the value of the senderAuthenticationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationDetailsType }
     *     
     */
    public void setSenderAuthenticationDetails(AuthenticationDetailsType value) {
        this.senderAuthenticationDetails = value;
    }

    /**
     * Gets the value of the recipientAuthenticationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationDetailsType }
     *     
     */
    public AuthenticationDetailsType getRecipientAuthenticationDetails() {
        return recipientAuthenticationDetails;
    }

    /**
     * Sets the value of the recipientAuthenticationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationDetailsType }
     *     
     */
    public void setRecipientAuthenticationDetails(AuthenticationDetailsType value) {
        this.recipientAuthenticationDetails = value;
    }

    /**
     * Gets the value of the eventTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEventTime() {
        return eventTime;
    }

    /**
     * Sets the value of the eventTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEventTime(XMLGregorianCalendar value) {
        this.eventTime = value;
    }

    /**
     * Gets the value of the submissionTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubmissionTime() {
        return submissionTime;
    }

    /**
     * Sets the value of the submissionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubmissionTime(XMLGregorianCalendar value) {
        this.submissionTime = value;
    }

    /**
     * Gets the value of the replyTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplyTo() {
        return replyTo;
    }

    /**
     * Sets the value of the replyTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplyTo(String value) {
        this.replyTo = value;
    }

    /**
     * Gets the value of the senderDetails property.
     * 
     * @return
     *     possible object is
     *     {@link EntityDetailsType }
     *     
     */
    public EntityDetailsType getSenderDetails() {
        return senderDetails;
    }

    /**
     * Sets the value of the senderDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityDetailsType }
     *     
     */
    public void setSenderDetails(EntityDetailsType value) {
        this.senderDetails = value;
    }

    /**
     * Gets the value of the recipientsDetails property.
     * 
     * @return
     *     possible object is
     *     {@link RecipientsDetails }
     *     
     */
    public RecipientsDetails getRecipientsDetails() {
        return recipientsDetails;
    }

    /**
     * Sets the value of the recipientsDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipientsDetails }
     *     
     */
    public void setRecipientsDetails(RecipientsDetails value) {
        this.recipientsDetails = value;
    }

    /**
     * Gets the value of the recipientsDelegatesDetails property.
     * 
     * @return
     *     possible object is
     *     {@link RecipientsDelegatesDetails }
     *     
     */
    public RecipientsDelegatesDetails getRecipientsDelegatesDetails() {
        return recipientsDelegatesDetails;
    }

    /**
     * Sets the value of the recipientsDelegatesDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipientsDelegatesDetails }
     *     
     */
    public void setRecipientsDelegatesDetails(RecipientsDelegatesDetails value) {
        this.recipientsDelegatesDetails = value;
    }

    /**
     * Gets the value of the evidenceRefersToRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEvidenceRefersToRecipient() {
        return evidenceRefersToRecipient;
    }

    /**
     * Sets the value of the evidenceRefersToRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEvidenceRefersToRecipient(BigInteger value) {
        this.evidenceRefersToRecipient = value;
    }

    /**
     * Gets the value of the senderMessageDetails property.
     * 
     * @return
     *     possible object is
     *     {@link MessageDetailsType }
     *     
     */
    public MessageDetailsType getSenderMessageDetails() {
        return senderMessageDetails;
    }

    /**
     * Sets the value of the senderMessageDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageDetailsType }
     *     
     */
    public void setSenderMessageDetails(MessageDetailsType value) {
        this.senderMessageDetails = value;
    }

    /**
     * Gets the value of the notificationMessageDetails property.
     * 
     * @return
     *     possible object is
     *     {@link MessageDetailsType }
     *     
     */
    public MessageDetailsType getNotificationMessageDetails() {
        return notificationMessageDetails;
    }

    /**
     * Sets the value of the notificationMessageDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageDetailsType }
     *     
     */
    public void setNotificationMessageDetails(MessageDetailsType value) {
        this.notificationMessageDetails = value;
    }

    /**
     * Gets the value of the forwardedToExternalSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForwardedToExternalSystem() {
        return forwardedToExternalSystem;
    }

    /**
     * Sets the value of the forwardedToExternalSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForwardedToExternalSystem(String value) {
        this.forwardedToExternalSystem = value;
    }

    /**
     * Gets the value of the transactionLogInformation property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionLogInformation }
     *     
     */
    public TransactionLogInformation getTransactionLogInformation() {
        return transactionLogInformation;
    }

    /**
     * Sets the value of the transactionLogInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionLogInformation }
     *     
     */
    public void setTransactionLogInformation(TransactionLogInformation value) {
        this.transactionLogInformation = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link Extensions }
     *     
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extensions }
     *     
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link Signature }
     *     
     */
    public Signature getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link Signature }
     *     
     */
    public void setSignature(Signature value) {
        this.signature = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
