/*
 * This file is part of epSOS OpenNCP implementation
 * Copyright (C) 2013  SPMS (Serviços Partilhados do Ministério da Saúde - Portugal)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact email: epsos@iuz.pt
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.21 at 08:42:10 AM WET 
//
package eu.epsos.pt.eadc.datamodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the eu.epsos.pt.eadc.datamodel package. <p>An
 * ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Transaction_QNAME = new QName("com:spirit:SpiritProxy", "Transaction");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: eu.epsos.pt.eadc.datamodel
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Transaction }
     *
     */
    public Transaction createComplexTypeTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link TransactionInfo }
     *
     */
    public TransactionInfo createComplexTypeTransactionInfo() {
        return new TransactionInfo();
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link Transaction }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "com:spirit:SpiritProxy", name = "Transaction")
    public JAXBElement<Transaction> createTransaction(Transaction value) {
        return new JAXBElement<Transaction>(_Transaction_QNAME, Transaction.class, null, value);
    }
}
