/*
 * This file is part of epSOS OpenNCP implementation
 * Copyright (C) 2013  SPMS (Serviços Partilhados do Ministério da Saúde - Portugal)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact email: epsos@iuz.pt
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.21 at 08:42:10 AM WET 
//


package eu.epsos.pt.eadc.datamodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexType_TransactionInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexType_TransactionInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Transaction_PK" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Direction" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HomeISO" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HomeNCP_OID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HomeHCID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HomeHost" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HomeAddress" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SndISO" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SndNCP_OID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SndHCID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SndAddress" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SndHost" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SndMsgID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ReceivingISO" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ReceivingNCP_OID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ReceivingHost" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="receivingAddr" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ReceivingMsgID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TransactionCounter" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HumanRequestor" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="UserId" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="POC" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="POC_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="AuthentificationLevel" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RequestAction" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ResponseAction" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ServiceType" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ServiceName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="StartTime" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="EndTime" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Duration" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexType_TransactionInfo")
public class TransactionInfo {

    @XmlAttribute(name = "Transaction_PK", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String transactionPK;
    @XmlAttribute(name = "Direction", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String direction;
    @XmlAttribute(name = "HomeISO", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String homeISO;
    @XmlAttribute(name = "HomeNCP_OID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String homeNCPOID;
    @XmlAttribute(name = "HomeHCID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String homeHCID;
    @XmlAttribute(name = "HomeHost", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String homeHost;
    @XmlAttribute(name = "HomeAddress", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String homeAddress;
    @XmlAttribute(name = "SndISO", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String sndISO;
    @XmlAttribute(name = "SndNCP_OID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String sndNCPOID;
    @XmlAttribute(name = "SndHCID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String sndHCID;
    @XmlAttribute(name = "SndAddress", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String sndAddress;
    @XmlAttribute(name = "SndHost", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String sndHost;
    @XmlAttribute(name = "SndMsgID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String sndMsgID;
    @XmlAttribute(name = "ReceivingISO")
    @XmlSchemaType(name = "anySimpleType")
    protected String receivingISO;
    @XmlAttribute(name = "ReceivingNCP_OID")
    @XmlSchemaType(name = "anySimpleType")
    protected String receivingNCPOID;
    @XmlAttribute(name = "ReceivingHost")
    @XmlSchemaType(name = "anySimpleType")
    protected String receivingHost;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String receivingAddr;
    @XmlAttribute(name = "ReceivingMsgID")
    @XmlSchemaType(name = "anySimpleType")
    protected String receivingMsgID;
    @XmlAttribute(name = "TransactionCounter", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String transactionCounter;
    @XmlAttribute(name = "HumanRequestor", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String humanRequestor;
    @XmlAttribute(name = "UserId", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String userId;
    @XmlAttribute(name = "POC", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String poc;
    @XmlAttribute(name = "POC_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String pocid;
    @XmlAttribute(name = "AuthentificationLevel", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String authentificationLevel;
    @XmlAttribute(name = "RequestAction", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String requestAction;
    @XmlAttribute(name = "ResponseAction", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String responseAction;
    @XmlAttribute(name = "ServiceType", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String serviceType;
    @XmlAttribute(name = "ServiceName", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String serviceName;
    @XmlAttribute(name = "StartTime", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String startTime;
    @XmlAttribute(name = "EndTime", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String endTime;
    @XmlAttribute(name = "Duration", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String duration;

    /**
     * Gets the value of the transactionPK property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionPK() {
        return transactionPK;
    }

    /**
     * Sets the value of the transactionPK property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionPK(String value) {
        this.transactionPK = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the homeISO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomeISO() {
        return homeISO;
    }

    /**
     * Sets the value of the homeISO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomeISO(String value) {
        this.homeISO = value;
    }

    /**
     * Gets the value of the homeNCPOID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomeNCPOID() {
        return homeNCPOID;
    }

    /**
     * Sets the value of the homeNCPOID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomeNCPOID(String value) {
        this.homeNCPOID = value;
    }

    /**
     * Gets the value of the homeHCID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomeHCID() {
        return homeHCID;
    }

    /**
     * Sets the value of the homeHCID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomeHCID(String value) {
        this.homeHCID = value;
    }

    /**
     * Gets the value of the homeHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomeHost() {
        return homeHost;
    }

    /**
     * Sets the value of the homeHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomeHost(String value) {
        this.homeHost = value;
    }

    /**
     * Gets the value of the homeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * Sets the value of the homeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomeAddress(String value) {
        this.homeAddress = value;
    }

    /**
     * Gets the value of the sndISO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndISO() {
        return sndISO;
    }

    /**
     * Sets the value of the sndISO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndISO(String value) {
        this.sndISO = value;
    }

    /**
     * Gets the value of the sndNCPOID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndNCPOID() {
        return sndNCPOID;
    }

    /**
     * Sets the value of the sndNCPOID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndNCPOID(String value) {
        this.sndNCPOID = value;
    }

    /**
     * Gets the value of the sndHCID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndHCID() {
        return sndHCID;
    }

    /**
     * Sets the value of the sndHCID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndHCID(String value) {
        this.sndHCID = value;
    }

    /**
     * Gets the value of the sndAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndAddress() {
        return sndAddress;
    }

    /**
     * Sets the value of the sndAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndAddress(String value) {
        this.sndAddress = value;
    }

    /**
     * Gets the value of the sndHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndHost() {
        return sndHost;
    }

    /**
     * Sets the value of the sndHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndHost(String value) {
        this.sndHost = value;
    }

    /**
     * Gets the value of the sndMsgID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndMsgID() {
        return sndMsgID;
    }

    /**
     * Sets the value of the sndMsgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndMsgID(String value) {
        this.sndMsgID = value;
    }

    /**
     * Gets the value of the receivingISO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceivingISO() {
        return receivingISO;
    }

    /**
     * Sets the value of the receivingISO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceivingISO(String value) {
        this.receivingISO = value;
    }

    /**
     * Gets the value of the receivingNCPOID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceivingNCPOID() {
        return receivingNCPOID;
    }

    /**
     * Sets the value of the receivingNCPOID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceivingNCPOID(String value) {
        this.receivingNCPOID = value;
    }

    /**
     * Gets the value of the receivingHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceivingHost() {
        return receivingHost;
    }

    /**
     * Sets the value of the receivingHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceivingHost(String value) {
        this.receivingHost = value;
    }

    /**
     * Gets the value of the receivingAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceivingAddr() {
        return receivingAddr;
    }

    /**
     * Sets the value of the receivingAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceivingAddr(String value) {
        this.receivingAddr = value;
    }

    /**
     * Gets the value of the receivingMsgID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceivingMsgID() {
        return receivingMsgID;
    }

    /**
     * Sets the value of the receivingMsgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceivingMsgID(String value) {
        this.receivingMsgID = value;
    }

    /**
     * Gets the value of the transactionCounter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionCounter() {
        return transactionCounter;
    }

    /**
     * Sets the value of the transactionCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionCounter(String value) {
        this.transactionCounter = value;
    }

    /**
     * Gets the value of the humanRequestor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHumanRequestor() {
        return humanRequestor;
    }

    /**
     * Sets the value of the humanRequestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHumanRequestor(String value) {
        this.humanRequestor = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the poc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOC() {
        return poc;
    }

    /**
     * Sets the value of the poc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOC(String value) {
        this.poc = value;
    }

    /**
     * Gets the value of the pocid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOCID() {
        return pocid;
    }

    /**
     * Sets the value of the pocid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOCID(String value) {
        this.pocid = value;
    }

    /**
     * Gets the value of the authentificationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthentificationLevel() {
        return authentificationLevel;
    }

    /**
     * Sets the value of the authentificationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthentificationLevel(String value) {
        this.authentificationLevel = value;
    }

    /**
     * Gets the value of the requestAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestAction() {
        return requestAction;
    }

    /**
     * Sets the value of the requestAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestAction(String value) {
        this.requestAction = value;
    }

    /**
     * Gets the value of the responseAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseAction() {
        return responseAction;
    }

    /**
     * Sets the value of the responseAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseAction(String value) {
        this.responseAction = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndTime(String value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

}
